
package et37.progredes.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraInterface", targetNamespace = "http://webservice.progredes.et37/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Sumar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Sumar", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.Sumar")
    @ResponseWrapper(localName = "SumarResponse", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.SumarResponse")
    @Action(input = "http://webservice.progredes.et37/CalculadoraInterface/SumarRequest", output = "http://webservice.progredes.et37/CalculadoraInterface/SumarResponse")
    public double sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Dividir")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Dividir", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.Dividir")
    @ResponseWrapper(localName = "DividirResponse", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.DividirResponse")
    @Action(input = "http://webservice.progredes.et37/CalculadoraInterface/DividirRequest", output = "http://webservice.progredes.et37/CalculadoraInterface/DividirResponse")
    public double dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Multiplicar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Multiplicar", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.Multiplicar")
    @ResponseWrapper(localName = "MultiplicarResponse", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.MultiplicarResponse")
    @Action(input = "http://webservice.progredes.et37/CalculadoraInterface/MultiplicarRequest", output = "http://webservice.progredes.et37/CalculadoraInterface/MultiplicarResponse")
    public double multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Restar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Restar", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.Restar")
    @ResponseWrapper(localName = "RestarResponse", targetNamespace = "http://webservice.progredes.et37/", className = "et37.progredes.webservice.RestarResponse")
    @Action(input = "http://webservice.progredes.et37/CalculadoraInterface/RestarRequest", output = "http://webservice.progredes.et37/CalculadoraInterface/RestarResponse")
    public double restar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
